spring:
  sql:
    init:
      encoding: utf-8
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database

roomescape:
  auth:
    jwt:
#      secret: ${sKey}
      secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E
